# Generated by Django 5.2.6 on 2025-09-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
